/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balldetection.manualControll;

import gcode.GcodeStreamer;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author greg
 */
public class manualControll extends javax.swing.JFrame {

    private static final int SPACE = 32;
    private static final int J = 74;
    private static final int K = 75;
    private static final int L = 76;
    private static final int SEMI = 59;
    private static final int LEFT = 37;
    private static final int RIGHT = 39;
    private static final int positions = 5;
    private static final int MAX = 420;
    private static final int MIN = 0;
    private static final int MOVESIZE = (MAX - MIN)/positions;
    private int target = 0;
    private int curPos = 0;
    private GcodeStreamer robot;
    
    private void moveRight() {
        if(target==MAX)return;
        target += this.MOVESIZE;
//        robot.moveXTo(target);
    }

    private void moveLeft() {
        if(target==MIN)return;
        target -= this.MOVESIZE;
//        robot.moveXTo(target);
    }
    private void updateLabel(){
        jLabel1.setText("" + target);
    }
    
    
    public manualControll() {
        initComponents();
        robot = new GcodeStreamer();
        addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent event) {
                switch (event.getKeyCode()) {
                    case SPACE:
                        target = 0;
                        break;
                    case J:
                        target = 105;
                        break;
                    case K:
                        target = 210;
                        break;
                    case L:
                        target = 315;
                        break;
                    case SEMI:
                        target = 420;
                        break;
//                    case LEFT:
//                        moveLeft();
//                        break;
//                    case RIGHT:
//                        moveRight();
//                        break;
                }
                robot.moveXTo(target);
                updateLabel();
            }
        });
        Timer t  = new Timer(); 
        t.schedule(new TimerTask() {

            @Override
            public void run() {
                try{ 

                } catch (Throwable ex) {
                    System.out.println("Failed to send new goal");
                }
            }
        }, 0, 10);
    }
    

  

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manualControll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manualControll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manualControll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manualControll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manualControll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
