/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balldetection.processors;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import org.opencv.core.Point;

/**
 *
 * @author greg
 */
public class WindowSelectingPane extends javax.swing.JFrame {

    public List<Point> getPoints(){
        List<Point> points = new ArrayList<>();

        points.add(getPoint(px1,py1));
        points.add(getPoint(px2,py2));
        points.add(getPoint(px3,py3));
        points.add(getPoint(px4,py4));
        return points;
    }
    
    
    
    /**
     * Creates new form WindowSelectingPane
     */
    public WindowSelectingPane() {
        initComponents();
        px1.setValue(5);
        py1.setValue(5);
        
        px2.setValue(460);
        py2.setValue(15);
        
        px3.setValue(5);
        py3.setValue(600);
        
        px4.setValue(460);
        py4.setValue(600);

        setSize(400,200);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        py1 = new javax.swing.JSpinner();
        px1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        py2 = new javax.swing.JSpinner();
        px2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        py3 = new javax.swing.JSpinner();
        px3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        py4 = new javax.swing.JSpinner();
        px4 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(365, 200));
        getContentPane().setLayout(null);
        getContentPane().add(py1);
        py1.setBounds(60, 60, 45, 20);
        getContentPane().add(px1);
        px1.setBounds(60, 40, 45, 20);

        jLabel1.setText("0");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 34, 14);

        jLabel2.setText("y");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 10, 14);

        jLabel3.setText("x");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 40, 10, 14);
        getContentPane().add(py2);
        py2.setBounds(110, 60, 45, 20);
        getContentPane().add(px2);
        px2.setBounds(110, 40, 45, 20);

        jLabel4.setText("0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 20, 34, 14);
        getContentPane().add(py3);
        py3.setBounds(160, 60, 45, 20);
        getContentPane().add(px3);
        px3.setBounds(160, 40, 45, 20);

        jLabel5.setText("0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 20, 34, 14);
        getContentPane().add(py4);
        py4.setBounds(210, 60, 45, 20);
        getContentPane().add(px4);
        px4.setBounds(210, 40, 45, 20);

        jLabel6.setText("0");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 20, 34, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner px1;
    private javax.swing.JSpinner px2;
    private javax.swing.JSpinner px3;
    private javax.swing.JSpinner px4;
    private javax.swing.JSpinner py1;
    private javax.swing.JSpinner py2;
    private javax.swing.JSpinner py3;
    private javax.swing.JSpinner py4;
    // End of variables declaration//GEN-END:variables

    private Point getPoint(JSpinner x, JSpinner y) {
        return new Point( getDoubleValue(x) , getDoubleValue(y));
    }
    
    private Double getDoubleValue(JSpinner val){
        return .0 + (int) val.getValue();
        
    }
}
