/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balldetection.processors;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import org.opencv.core.Point;

/**
 *
 * @author greg
 */
public class WindowSelectingPane extends javax.swing.JFrame {

    public List<Point> getPoints(){
        List<Point> points = new ArrayList<>();
        points.add(getPoint(tlx,tly));
        points.add(getPoint(blx,bly));
        points.add(getPoint(trx,trY));
        points.add(getPoint(brx,bry));
        return points;
    }
    
    
    
    /**
     * Creates new form WindowSelectingPane
     */
    public WindowSelectingPane() {
        initComponents();
        setSize(400,200);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlx = new javax.swing.JSpinner();
        tly = new javax.swing.JSpinner();
        trx = new javax.swing.JSpinner();
        trY = new javax.swing.JSpinner();
        blx = new javax.swing.JSpinner();
        bly = new javax.swing.JSpinner();
        brx = new javax.swing.JSpinner();
        bry = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(365, 200));
        setLayout(null);
        add(tlx);
        tlx.setBounds(10, 25, 45, 20);
        add(tly);
        tly.setBounds(61, 25, 51, 20);

        trx.setValue(480);
        add(trx);
        trx.setBounds(200, 30, 48, 20);

        trY.setValue(0
        );
        add(trY);
        trY.setBounds(250, 30, 44, 20);

        blx.setValue(640);
        add(blx);
        blx.setBounds(10, 51, 45, 20);

        bly.setValue(0);
        add(bly);
        bly.setBounds(61, 51, 51, 20);

        brx.setValue(480);
        add(brx);
        brx.setBounds(200, 50, 48, 20);

        bry.setValue(640);
        add(bry);
        bry.setBounds(250, 50, 44, 20);

        jLabel1.setText("Top Left");
        add(jLabel1);
        jLabel1.setBounds(130, 30, 40, 14);

        jLabel2.setText("Top Right");
        add(jLabel2);
        jLabel2.setBounds(310, 30, 46, 14);

        jLabel3.setText("Bottom Left");
        add(jLabel3);
        jLabel3.setBounds(130, 50, 56, 14);

        jLabel4.setText("Bottom Right");
        add(jLabel4);
        jLabel4.setBounds(300, 50, 62, 14);

        jLabel5.setText("x");
        add(jLabel5);
        jLabel5.setBounds(15, 5, 20, 14);

        jLabel6.setText("x");
        add(jLabel6);
        jLabel6.setBounds(220, 0, 6, 14);

        jLabel7.setText("    y");
        add(jLabel7);
        jLabel7.setBounds(260, 0, 18, 14);

        jLabel8.setText("    y");
        add(jLabel8);
        jLabel8.setBounds(61, 5, 18, 14);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner blx;
    private javax.swing.JSpinner bly;
    private javax.swing.JSpinner brx;
    private javax.swing.JSpinner bry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner tlx;
    private javax.swing.JSpinner tly;
    private javax.swing.JSpinner trY;
    private javax.swing.JSpinner trx;
    // End of variables declaration//GEN-END:variables

    private Point getPoint(JSpinner x, JSpinner y) {
        return new Point( getDoubleValue(x) , getDoubleValue(y));
    }
    
    private Double getDoubleValue(JSpinner val){
        return .0 + (int) val.getValue();
        
    }
}
