/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thermite.pongbotcontroller;

import java.awt.event.KeyEvent;

/**
 *
 * @author gregor
 */
public class BotController extends javax.swing.JFrame {

    /**
     * Creates new form BotController
     */
    private State state;

    public BotController() {
        initComponents();
        state = new State();
        state.setPaddle((byte) 0);
        state.setMove((byte) 0);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        runPaddle = new javax.swing.JToggleButton();
        paddleSpeed = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        botSpeed = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        moveLeft = new javax.swing.JButton();
        moveRight = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runPaddle.setText("Run Paddle");

        paddleSpeed.setMaximum(255);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paddleSpeed, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        botSpeed.setMaximum(255);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, botSpeed, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        moveLeft.setText("LEFT");
        moveLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveLeftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveLeftMouseReleased(evt);
            }
        });
        moveLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLeftActionPerformed(evt);
            }
        });

        moveRight.setText("RIGHT");
        moveRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveRightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveRightMouseReleased(evt);
            }
        });

        jButton1.setText("CLICK HERE TO ENABLE KEYBOARD CONTROL");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(runPaddle)
                                .addGap(18, 18, 18)
                                .addComponent(paddleSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botSpeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(moveLeft)
                        .addGap(47, 47, 47)
                        .addComponent(moveRight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(paddleSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(runPaddle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveLeft)
                    .addComponent(moveRight))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLeftActionPerformed


    }//GEN-LAST:event_moveLeftActionPerformed

    private void moveLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveLeftMousePressed
        state.setMove(State.FORWARD);
        state.setMoveSpeed((byte) botSpeed.getValue());


    }//GEN-LAST:event_moveLeftMousePressed

    private void moveRightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveRightMousePressed
        state.setMove(State.BACKWARD);
        state.setMoveSpeed((byte) botSpeed.getValue());

    }//GEN-LAST:event_moveRightMousePressed

    private void moveLeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveLeftMouseReleased
        state.setMoveSpeed(State.STOP);
    }//GEN-LAST:event_moveLeftMouseReleased

    private void moveRightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveRightMouseReleased
        state.setMoveSpeed((byte) 0);
    }//GEN-LAST:event_moveRightMouseReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_LEFT:
                moveRightMousePressed(null);
                break;
            case KeyEvent.VK_RIGHT:
                moveLeftMousePressed(null);
                break;
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        state.setMove(State.STOP);
    }//GEN-LAST:event_jButton1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider botSpeed;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton moveLeft;
    private javax.swing.JButton moveRight;
    private javax.swing.JSlider paddleSpeed;
    private javax.swing.JToggleButton runPaddle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public State getStateObject() {
        updateState();

        return state;
    }

    private void updateState() {
        if (runPaddle.isSelected()) {
            state.setPaddleSpeed((byte) paddleSpeed.getValue());
        } else {
            state.setPaddleSpeed((byte) 0);
        }

    }

}
